months = int(input("How many months? "))
pairsperpair = int(input("How many pairs of rabbits does each pair produce per month? "))

def fibseq(months, pairsperpair):
    if months == 0 or months == 1:
        return months
    elif months > 1:
        return (fibseq(months-1, pairsperpair)+ pairsperpair * fibseq(months-2, pairsperpair)) # the pairsperpair multiplied by the fibseq of months-2 is to include the offspring generated by the previous generation as well as the current generation.

print(fibseq(months, pairsperpair))
